### ISSUE TITLE
world reload issue

### ISSUE THREAD

**Issue by TheNimbleNinja** [Arathain/malazan#1]
with your mod in my pack its causing other mods to error and cause data back loading issues

**Comment by TheNimbleNinja** [comment]
https://gist.github.com/TheNimbleNinja/10e3434e030cf3d9ef33508f0c262ea7

**Comment by Arathain** [comment]
Are you sure it's an issue with malazan itself? I wouldn't be surprised, but the crash log doesn't show my mod to be liable, therefore I don't know *what* went wrong

**Comment by TheNimbleNinja** [comment]
your mod is causing other mods to fail as your mod is trying to load there structures and causing them to be null

**Comment by FoundationGames** [comment]
Could you describe what other mods you are loading Malazan with that causes the data pack load issue?

**Comment by TheNimbleNinja** [comment]
im using 300+ different mods so i cant

**Comment by Arathain** [comment]
fixed? idk modfest's over anyway
